// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkDaTXbaN41wPDDQ14pJYiqaDaOFS9PFQ',
    appId: '1:861358488174:web:70ecef267020f7a0a3047f',
    messagingSenderId: '861358488174',
    projectId: 'colegiosoftwaremr',
    authDomain: 'colegiosoftwaremr.firebaseapp.com',
    storageBucket: 'colegiosoftwaremr.firebasestorage.app',
    measurementId: 'G-37JQX24SMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB21aqIhuZ56rPOXM3qinXGd4lEXHthZnY',
    appId: '1:861358488174:android:52e6d50d8aa89516a3047f',
    messagingSenderId: '861358488174',
    projectId: 'colegiosoftwaremr',
    storageBucket: 'colegiosoftwaremr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HVAgEsN3dXUQ_QKBwyxMI89G8kr5wSI',
    appId: '1:861358488174:ios:34cbc56ed35ea0eca3047f',
    messagingSenderId: '861358488174',
    projectId: 'colegiosoftwaremr',
    storageBucket: 'colegiosoftwaremr.firebasestorage.app',
    iosBundleId: 'com.example.colegiosoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HVAgEsN3dXUQ_QKBwyxMI89G8kr5wSI',
    appId: '1:861358488174:ios:1c7c275bf44c4320a3047f',
    messagingSenderId: '861358488174',
    projectId: 'colegiosoftwaremr',
    storageBucket: 'colegiosoftwaremr.firebasestorage.app',
    iosBundleId: 'com.blacklabel.mariareyn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkDaTXbaN41wPDDQ14pJYiqaDaOFS9PFQ',
    appId: '1:861358488174:web:85d6fabfbb2985d3a3047f',
    messagingSenderId: '861358488174',
    projectId: 'colegiosoftwaremr',
    authDomain: 'colegiosoftwaremr.firebaseapp.com',
    storageBucket: 'colegiosoftwaremr.firebasestorage.app',
    measurementId: 'G-B68ZP18F75',
  );
}
